apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: java-prod
namePrefix: prod-

images:
  - name: YOUR_DOCKERHUB_USERNAME/java-screening-app
    newTag: sha-3f7bd03
