apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring