apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: homelab-k3s
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
spec:
  apiUrl: https://clo29412.live.dynatrace.com/api
  tokens: homelab-k3s
  activeGate:
    capabilities:
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    replicas: 1
  templates:
    otelCollector:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-otel-collector
        tag: latest
  telemetryIngest:
    protocols:
      - otlp
    serviceName: telemetry-ingest
---
apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: homelab-k3s-agents
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
spec:
  apiUrl: https://clo29412.live.dynatrace.com/api
  tokens: homelab-k3s
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - debugging
    resources:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    replicas: 1
  logMonitoring: {}
