apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: monitoring
  labels:
    app: splunk
spec:
  selector:
    app: splunk
  ports:
    - port: 8000
      targetPort: 8000
      name: web
    - port: 8088
      targetPort: 8088
      name: hec
  type: ClusterIP