apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-python-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fazabillah/devops-homelab
    targetRevision: HEAD
    path: kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true