apiVersion: v1
kind: Service
metadata:
  name: homelab-python-app
  labels:
    app: homelab-python-app
spec:
  selector:
    app: homelab-python-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP