apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: app-dev

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: docker.io/fazabillah/homelab-python-app
    newTag: sha-f2277da

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug